주차구역 EV 점유 타이머 API: parking_timer::TimerManager Class Reference
parking_timer::TimerManager Class Reference
#include <TimerManager.hpp>
Data Structures
struct LaterDeadline
struct TimerItem
Public Types
using ViolationCallback = std::function< void(const ViolationEvent &)>
using ErrorCallback = std::function< void(const TimerError &)>
Public Member Functions
TimerManager (EventDatabase &database, ViolationCallback callback, ErrorCallback error_callback={}, std::mutex *transition_mutex=nullptr)
DB와 callback을 연결하고 단일 타이머 worker 스레드를 시작한다.
~TimerManager ()
worker에 종료를 알리고 스레드가 완전히 끝날 때까지 기다린다.
TimerManager (const TimerManager &)=delete
TimerManager & operator= (const TimerManager &)=delete
void schedule (std::int64_t log_id, int zone_id, std::string car_number, std::chrono::milliseconds delay)
주차 세션의 만료시각을 계산해 최소 우선순위 큐에 등록한다.
std::size_t pendingCount () const
실제 우선순위 큐에 남아 있는 노드 수를 반환한다.
Private Types
using Clock = std::chrono::steady_clock
Private Member Functions
void run ()
가장 이른 deadline만 기다리며 만료 노드를 처리하는 worker 루프.
void processExpired (TimerItem item)
만료 노드를 DB 조건부 UPDATE로 검증하고 위반 callback을 발생시킨다.
void retryAfterDatabaseError (TimerItem item, std::string message) noexcept
일시적인 SQLite 오류가 난 타이머를 지수 backoff로 다시 예약한다.
void reportError (const TimerItem &item, std::string message) noexcept
타이머 오류를 등록된 callback 또는 표준 오류 출력으로 안전하게 보고한다.
Private Attributes
EventDatabase & database_
ViolationCallback callback_
ErrorCallback error_callback_
std::mutex * transition_mutex_ {}
std::mutex mutex_
std::condition_variable cv_
std::priority_queue< TimerItem, std::vector< TimerItem >, LaterDeadline > queue_
bool stopping_ {}
std::uint64_t next_sequence_ {}
std::thread worker_
Detailed Description
Definition at line 32 of file TimerManager.hpp.
Member Typedef Documentation
Clock
using parking_timer::TimerManager::Clock = std::chrono::steady_clock private
Definition at line 54 of file TimerManager.hpp.
ErrorCallback
using parking_timer::TimerManager::ErrorCallback = std::function<void(const TimerError&)>
Definition at line 35 of file TimerManager.hpp.
ViolationCallback
using parking_timer::TimerManager::ViolationCallback = std::function<void(const ViolationEvent&)>
Definition at line 34 of file TimerManager.hpp.
Constructor & Destructor Documentation
TimerManager() [1/2]
parking_timer::TimerManager::TimerManager (EventDatabase & database, ViolationCallback callback, ErrorCallback error_callback = {}, std::mutex * transition_mutex = nullptr)
DB와 callback을 연결하고 단일 타이머 worker 스레드를 시작한다.
Parameters
[in,out] database 만료 시 로그 상태를 바꿀 SQLite 접근 객체.
[in] callback 위반 확정 후 호출할 callback.
[in] error_callback worker 오류를 보고할 선택 callback.
[in,out] transition_mutex 입차·출차·만료 전이를 직렬화할 선택 mutex 포인터.
Exceptions
std::system_error worker 스레드를 생성할 수 없는 경우.
Note
참조와 mutex는 이 TimerManager보다 오래 살아 있어야 한다.
Definition at line 39 of file TimerManager.cpp.
References reportError(), run(), and worker_.
~TimerManager()
parking_timer::TimerManager::~TimerManager ()
worker에 종료를 알리고 스레드가 완전히 끝날 때까지 기다린다.
Note
stop flag 설정 → condition variable 깨우기 → join 순서를 지켜 소멸 후 callback이 외부 객체를 참조하는 일을 막는다. 큐의 미만료 항목은 소멸 시 처리하지 않는다.
Definition at line 66 of file TimerManager.cpp.
References cv_, mutex_, stopping_, and worker_.
TimerManager() [2/2]
parking_timer::TimerManager::TimerManager (const TimerManager &) delete
Member Function Documentation
operator=()
TimerManager & parking_timer::TimerManager::operator= (const TimerManager &) delete
pendingCount()
std::size_t parking_timer::TimerManager::pendingCount () const
실제 우선순위 큐에 남아 있는 노드 수를 반환한다.
Returns
활성 노드, DB 재시도 노드, 아직 만료되지 않은 lazy-canceled 노드를 모두 포함한 수.
Definition at line 119 of file TimerManager.cpp.
References mutex_, and queue_.
Referenced by parking_timer::ParkingSlotManager::pendingTimerCount().
processExpired()
void parking_timer::TimerManager::processExpired (TimerItem item) private
만료 노드를 DB 조건부 UPDATE로 검증하고 위반 callback을 발생시킨다.
Parameters
[in] item 큐에서 제거된 만료 타이머 항목.
Note
출차와 동시에 실행되면 공용 전이 mutex를 먼저 얻은 처리가 우선한다. DB UPDATE가 0행인 경우는 이미 출차·취소된 정상 lazy deletion 경로이므로 callback하지 않는다.
Definition at line 175 of file TimerManager.cpp.
References callback_, parking_timer::TimerManager::TimerItem::car_number, database_, parking_timer::TimerManager::TimerItem::log_id, parking_timer::EventDatabase::markViolation(), reportError(), retryAfterDatabaseError(), transition_mutex_, parking_timer::utcNow(), parking_timer::TimerManager::TimerItem::violation_at, and parking_timer::TimerManager::TimerItem::zone_id.
Referenced by run().
reportError()
void parking_timer::TimerManager::reportError (const TimerItem & item, std::string message) private noexcept
타이머 오류를 등록된 callback 또는 표준 오류 출력으로 안전하게 보고한다.
Parameters
[in] item 오류가 발생한 타이머 문맥. 루프 자체 오류면 기본값일 수 있다.
[in] message 오류 설명.
Note
오류 callback 자체가 예외를 던져도 흡수해 std::terminate를 방지한다.
Definition at line 276 of file TimerManager.cpp.
References parking_timer::TimerError::log_id.
Referenced by processExpired(), and TimerManager().
retryAfterDatabaseError()
void parking_timer::TimerManager::retryAfterDatabaseError (TimerItem item, std::string message) private noexcept
일시적인 SQLite 오류가 난 타이머를 지수 backoff로 다시 예약한다.
Parameters
[in] item DB 갱신에 실패한 만료 항목. 최초 위반 시각을 그대로 보존한다.
[in] message 오류 callback에 전달할 SQLite 오류 설명.
Note
재시도 간격은 1, 2, 4, 8, 16, 32초이며 이후 32초로 포화된다. 모든 내부 예외를 흡수하므로 worker 스레드 밖으로 예외를 던지지 않는다.
Definition at line 233 of file TimerManager.cpp.
Referenced by processExpired().
run()
void parking_timer::TimerManager::run () private
가장 이른 deadline만 기다리며 만료 노드를 처리하는 worker 루프.
Note
큐가 비면 무기한 대기하고, 항목이 있으면 top의 deadline까지 wait_until()한다. DB 작업 중에는 큐 mutex를 풀어 다른 스레드의 schedule()을 막지 않는다.
Definition at line 130 of file TimerManager.cpp.
References cv_, mutex_, processExpired(), queue_, and stopping_.
Referenced by TimerManager().
schedule()
void parking_timer::TimerManager::schedule (std::int64_t log_id, int zone_id, std::string car_number, std::chrono::milliseconds delay)
주차 세션의 만료시각을 계산해 최소 우선순위 큐에 등록한다.
Parameters
[in] log_id timer_log의 불변 세션 ID.
[in] zone_id 충전구역 ID.
[in] car_number 차량번호. 큐 항목이 자체 소유하도록 값으로 받는다.
[in] delay 현재부터 만료까지의 단조시간 간격.
Exceptions
std::invalid_argument delay가 0 이하인 경우.
std::runtime_error 관리자가 이미 종료 중인 경우.
Definition at line 87 of file TimerManager.cpp.
References cv_, mutex_, next_sequence_, queue_, and stopping_.
Referenced by parking_timer::ParkingSlotManager::handleEntry(), anonymous_namespace{timer_tests.cpp}::testEarlierDeadlineWakesWorker(), and anonymous_namespace{timer_tests.cpp}::testWorkerContainsCallbackExceptions().
Field Documentation
callback_
ViolationCallback parking_timer::TimerManager::callback_ private
Definition at line 77 of file TimerManager.hpp.
Referenced by processExpired().
cv_
std::condition_variable parking_timer::TimerManager::cv_ private
Definition at line 81 of file TimerManager.hpp.
Referenced by run(), schedule(), and ~TimerManager().
database_
EventDatabase& parking_timer::TimerManager::database_ private
Definition at line 76 of file TimerManager.hpp.
Referenced by processExpired().
error_callback_
ErrorCallback parking_timer::TimerManager::error_callback_ private
Definition at line 78 of file TimerManager.hpp.
mutex_
std::mutex parking_timer::TimerManager::mutex_ mutable private
Definition at line 80 of file TimerManager.hpp.
Referenced by pendingCount(), run(), schedule(), and ~TimerManager().
next_sequence_
std::uint64_t parking_timer::TimerManager::next_sequence_ {} private
Definition at line 84 of file TimerManager.hpp.
Referenced by schedule().
queue_
std::priority_queue<TimerItem, std::vector<TimerItem>, LaterDeadline> parking_timer::TimerManager::queue_ private
Definition at line 82 of file TimerManager.hpp.
Referenced by pendingCount(), run(), and schedule().
stopping_
bool parking_timer::TimerManager::stopping_ {} private
Definition at line 83 of file TimerManager.hpp.
Referenced by run(), schedule(), and ~TimerManager().
transition_mutex_
std::mutex* parking_timer::TimerManager::transition_mutex_ {} private
Definition at line 79 of file TimerManager.hpp.
Referenced by processExpired().
worker_
std::thread parking_timer::TimerManager::worker_ private
Definition at line 86 of file TimerManager.hpp.
Referenced by TimerManager(), and ~TimerManager().
The documentation for this class was generated from the following files:
TimerManager.hpp
TimerManager.cpp