주차구역 EV 점유 타이머 API: parking_timer::ParkingSlotManager Class Reference
parking_timer::ParkingSlotManager Class Reference
#include <ParkingSlotManager.hpp>
Public Member Functions
ParkingSlotManager (EventDatabase &database, EventManager &events, std::chrono::milliseconds parking_timeout)
입·출차 상태 전이와 EV 점유 타이머를 조정하는 관리자를 생성한다.
EntryResult handleEntry (int zone_id, const std::string &car_number, const std::string &image_path_1={})
홀센서 OFF→ON과 번호판 인식 결과에 해당하는 입차 이벤트를 처리한다.
std::optional< LogRecord > handleExit (int zone_id)
홀센서 ON→OFF에 해당하는 출차 이벤트를 처리한다.
std::size_t pendingTimerCount () const
큐에 남아 있는 타이머 노드 수를 조회한다.
Private Attributes
EventDatabase & database_
EventManager & events_
std::chrono::milliseconds parking_timeout_
std::mutex transition_mutex_
TimerManager timers_
Detailed Description
Definition at line 13 of file ParkingSlotManager.hpp.
Constructor & Destructor Documentation
ParkingSlotManager()
parking_timer::ParkingSlotManager::ParkingSlotManager (EventDatabase & database, EventManager & events, std::chrono::milliseconds parking_timeout)
입·출차 상태 전이와 EV 점유 타이머를 조정하는 관리자를 생성한다.
Parameters
[in,out] database 차량 조회와 세션 로그를 저장할 SQLite 접근 객체.
[in,out] events 관제 이벤트를 발행할 이벤트 관리자.
[in] parking_timeout EV/PHEV 장기점유 판정까지의 대기시간.
Exceptions
std::invalid_argument 제한시간이 0 이하인 경우.
std::system_error 타이머 worker 스레드를 생성할 수 없는 경우.
Note
타이머 callback과 출차 처리는 같은 transition_mutex_를 사용하므로 DB 상태와 이벤트 발행 순서가 서로 뒤집히지 않는다.
Definition at line 21 of file ParkingSlotManager.cpp.
References events_, and parking_timer::EventManager::publish().
Member Function Documentation
handleEntry()
EntryResult parking_timer::ParkingSlotManager::handleEntry (int zone_id, const std::string & car_number, const std::string & image_path_1 = {})
홀센서 OFF→ON과 번호판 인식 결과에 해당하는 입차 이벤트를 처리한다.
Parameters
[in] zone_id 차량이 들어온 충전구역 ID. 1 이상의 값이어야 한다.
[in] car_number 차량 마스터에서 조회할 번호판 문자열.
[in] image_path_1 최초 주차 증거 이미지 경로. 비어 있으면 기본 경로를 만든다.
Returns
타이머 등록 여부, 차량 분류, 생성된 로그 ID와 설명을 담은 결과.
Exceptions
std::invalid_argument 구역 ID가 잘못됐거나 차량번호가 비어 있는 경우.
std::runtime_error SQLite 처리 또는 타이머 등록에 실패한 경우.
Definition at line 51 of file ParkingSlotManager.cpp.
References parking_timer::EventDatabase::cancelUnscheduled(), parking_timer::EventDatabase::classifyVehicle(), database_, events_, parking_timer::EventDatabase::findActiveByZone(), parking_timer::EventDatabase::insertParked(), parking_timer::NonEv, parking_timeout_, parking_timer::EventManager::publish(), parking_timer::TimerManager::schedule(), timers_, transition_mutex_, parking_timer::Unknown, and parking_timer::utcNow().
Referenced by anonymous_namespace{main.cpp}::runDemo(), anonymous_namespace{main.cpp}::runInteractive(), and anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit().
handleExit()
std::optional< LogRecord > parking_timer::ParkingSlotManager::handleExit (int zone_id)
홀센서 ON→OFF에 해당하는 출차 이벤트를 처리한다.
Parameters
[in] zone_id 차량이 빠져나온 충전구역 ID.
Returns
갱신된 로그. 활성 세션이 없으면 std::nullopt.
Exceptions
std::invalid_argument 구역 ID가 0 이하인 경우.
std::runtime_error SQLite 트랜잭션 처리에 실패한 경우.
Note
우선순위 큐에서 임의 원소를 제거하지 않고 DB의 is_canceled를 표시한다.
Definition at line 114 of file ParkingSlotManager.cpp.
References database_, parking_timer::EventDatabase::departActiveByZone(), events_, parking_timer::EventManager::publish(), transition_mutex_, and parking_timer::utcNow().
Referenced by anonymous_namespace{main.cpp}::runDemo(), anonymous_namespace{main.cpp}::runInteractive(), and anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit().
pendingTimerCount()
std::size_t parking_timer::ParkingSlotManager::pendingTimerCount () const
큐에 남아 있는 타이머 노드 수를 조회한다.
Returns
만료 전 활성 노드와 아직 top에 오지 않은 lazy-canceled 노드의 합계.
Definition at line 138 of file ParkingSlotManager.cpp.
References parking_timer::TimerManager::pendingCount(), and timers_.
Referenced by anonymous_namespace{main.cpp}::runInteractive(), and anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit().
Field Documentation
database_
EventDatabase& parking_timer::ParkingSlotManager::database_ private
Definition at line 27 of file ParkingSlotManager.hpp.
Referenced by handleEntry(), and handleExit().
events_
EventManager& parking_timer::ParkingSlotManager::events_ private
Definition at line 28 of file ParkingSlotManager.hpp.
Referenced by handleEntry(), handleExit(), and ParkingSlotManager().
parking_timeout_
std::chrono::milliseconds parking_timer::ParkingSlotManager::parking_timeout_ private
Definition at line 29 of file ParkingSlotManager.hpp.
Referenced by handleEntry().
timers_
TimerManager parking_timer::ParkingSlotManager::timers_ private
Definition at line 32 of file ParkingSlotManager.hpp.
Referenced by handleEntry(), and pendingTimerCount().
transition_mutex_
std::mutex parking_timer::ParkingSlotManager::transition_mutex_ private
Definition at line 31 of file ParkingSlotManager.hpp.
Referenced by handleEntry(), and handleExit().
The documentation for this class was generated from the following files:
ParkingSlotManager.hpp
ParkingSlotManager.cpp