주차구역 EV 점유 타이머 API: parking_timer::EventManager Class Reference
parking_timer::EventManager Class Reference
#include <EventManager.hpp>
Public Member Functions
void publish (std::string_view event_type, int zone_id, std::string_view car_number, std::string_view occurred_at, std::string_view detail={})
관제 시스템으로 보낼 이벤트를 한 줄 JSON 형태로 표준 출력에 발행한다.
Private Attributes
std::mutex output_mutex_
Detailed Description
Definition at line 12 of file EventManager.hpp.
Member Function Documentation
publish()
void parking_timer::EventManager::publish (std::string_view event_type, int zone_id, std::string_view car_number, std::string_view occurred_at, std::string_view detail = {})
관제 시스템으로 보낼 이벤트를 한 줄 JSON 형태로 표준 출력에 발행한다.
Parameters
[in] event_type ARRIVAL, DEPARTURE, VIOLATION_TRIGGERED 등의 이벤트 종류.
[in] zone_id 이벤트가 발생한 충전구역 ID.
[in] car_number 인식된 차량번호. 차량이 없으면 빈 문자열일 수 있다.
[in] occurred_at 이벤트 발생 UTC 시각.
[in] detail 선택적인 상세 메시지 또는 증거 이미지 경로.
Note
여러 스레드에서 호출되어도 JSON 한 줄이 서로 섞이지 않도록 출력 mutex를 잡는다.
Definition at line 61 of file EventManager.cpp.
References output_mutex_.
Referenced by parking_timer::ParkingSlotManager::handleEntry(), parking_timer::ParkingSlotManager::handleExit(), and parking_timer::ParkingSlotManager::ParkingSlotManager().
Field Documentation
output_mutex_
std::mutex parking_timer::EventManager::output_mutex_ private
Definition at line 21 of file EventManager.hpp.
Referenced by publish().
The documentation for this class was generated from the following files:
EventManager.hpp
EventManager.cpp