주차구역 EV 점유 타이머 API: parking_timer::EventDatabase Class Reference
parking_timer::EventDatabase Class Reference
#include <EventDatabase.hpp>
Public Member Functions
EventDatabase (const std::filesystem::path &database_path)
SQLite 이벤트 DB를 열고 프로토타입에 필요한 연결 옵션을 설정한다.
~EventDatabase ()
보유한 SQLite 연결을 닫는다.
EventDatabase (const EventDatabase &)=delete
EventDatabase & operator= (const EventDatabase &)=delete
void initialize (const std::filesystem::path &schema_file, const std::filesystem::path &seed_file)
스키마를 생성하고 차량 마스터 테스트 데이터를 멱등하게 삽입한다.
VehicleCategory classifyVehicle (std::string_view car_number) const
차량번호를 마스터 테이블에서 조회해 EV 분류를 반환한다.
std::int64_t insertParked (const std::string &car_number, int zone_id, const std::string &parked_at, const std::string &image_path_1)
EV/PHEV 입차 세션을 PARKED 상태로 INSERT한다.
bool markViolation (std::int64_t log_id, const std::string &violation_at, const std::string &image_path_2)
아직 활성인 주차 세션을 위반 상태로 조건부 갱신한다.
bool cancelUnscheduled (std::int64_t log_id, const std::string &canceled_at)
DB INSERT 후 큐 등록에 실패한 세션을 보상 종료한다.
std::optional< LogRecord > departActiveByZone (int zone_id, const std::string &departed_at)
지정 구역의 활성 세션을 출차 완료 상태로 원자적으로 갱신한다.
std::optional< LogRecord > findActiveByZone (int zone_id) const
지정 구역에서 아직 출차하지 않은 세션을 조회한다.
std::optional< LogRecord > findLogById (std::int64_t log_id) const
고유 로그 ID로 주차 세션 한 건을 조회한다.
std::vector< LogRecord > listLogs () const
모든 타이머 로그를 생성 순서대로 조회한다.
std::vector< std::pair< std::string, std::string > > listVehicles () const
차량 마스터의 차량번호와 차량 종류를 모두 조회한다.
void clearTimerLogs ()
데모를 새로 시작할 수 있도록 타이머 로그와 자동 증가 번호를 초기화한다.
Private Member Functions
void executeSqlUnlocked (const std::string &sql)
준비 과정이 필요 없는 SQL 문자열을 SQLite 연결에서 직접 실행한다.
Static Private Member Functions
static std::string readTextFile (const std::filesystem::path &path)
SQL/config 보조 파일 전체를 문자열로 읽는다.
Private Attributes
sqlite3 * db_ {}
std::mutex mutex_
Detailed Description
Definition at line 17 of file EventDatabase.hpp.
Constructor & Destructor Documentation
EventDatabase() [1/2]
parking_timer::EventDatabase::EventDatabase (const std::filesystem::path & database_path) explicit
SQLite 이벤트 DB를 열고 프로토타입에 필요한 연결 옵션을 설정한다.
Parameters
[in] database_path 열거나 새로 만들 SQLite 파일 경로. :memory:도 가능하다.
Exceptions
std::filesystem::filesystem_error 상위 디렉터리 생성에 실패한 경우.
std::runtime_error DB open 또는 PRAGMA 설정에 실패한 경우.
Note
foreign key, 3초 busy timeout, WAL 모드를 연결 생성 직후 활성화한다.
Definition at line 176 of file EventDatabase.cpp.
References db_, and executeSqlUnlocked().
~EventDatabase()
parking_timer::EventDatabase::~EventDatabase ()
보유한 SQLite 연결을 닫는다.
Definition at line 210 of file EventDatabase.cpp.
References db_.
EventDatabase() [2/2]
parking_timer::EventDatabase::EventDatabase (const EventDatabase &) delete
Member Function Documentation
cancelUnscheduled()
bool parking_timer::EventDatabase::cancelUnscheduled (std::int64_t log_id, const std::string & canceled_at)
DB INSERT 후 큐 등록에 실패한 세션을 보상 종료한다.
Parameters
[in] log_id 종료할 주차 세션 ID.
[in] canceled_at 보상 종료 UTC 시각.
Returns
활성 PARKED 행 한 개가 종료됐으면 true.
Exceptions
std::runtime_error SQLite UPDATE가 실패한 경우.
Definition at line 336 of file EventDatabase.cpp.
References db_, and mutex_.
Referenced by parking_timer::ParkingSlotManager::handleEntry().
classifyVehicle()
VehicleCategory parking_timer::EventDatabase::classifyVehicle (std::string_view car_number) const
차량번호를 마스터 테이블에서 조회해 EV 분류를 반환한다.
Parameters
[in] car_number 조회할 차량번호.
Returns
EV, PHEV, 일반차 또는 미등록(Unknown) 분류.
Exceptions
std::runtime_error SQLite 조회가 실패한 경우.
Definition at line 248 of file EventDatabase.cpp.
References db_, parking_timer::Ev, mutex_, parking_timer::NonEv, parking_timer::Phev, and parking_timer::Unknown.
Referenced by parking_timer::ParkingSlotManager::handleEntry(), and anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit().
clearTimerLogs()
void parking_timer::EventDatabase::clearTimerLogs ()
데모를 새로 시작할 수 있도록 타이머 로그와 자동 증가 번호를 초기화한다.
Exceptions
std::runtime_error DELETE SQL 실행이 실패한 경우.
Warning
운영 데이터에는 사용하지 말고 --reset-logs 데모 옵션에서만 사용한다.
Definition at line 528 of file EventDatabase.cpp.
References executeSqlUnlocked(), and mutex_.
departActiveByZone()
std::optional< LogRecord > parking_timer::EventDatabase::departActiveByZone (int zone_id, const std::string & departed_at)
지정 구역의 활성 세션을 출차 완료 상태로 원자적으로 갱신한다.
Parameters
[in] zone_id 출차가 감지된 충전구역 ID.
[in] departed_at 출차 UTC 시각.
Returns
갱신된 로그. 활성 세션이 없으면 std::nullopt.
Exceptions
std::runtime_error 조회·UPDATE·재조회 중 하나라도 실패한 경우.
Note
위반 후 출차도 최종 status는 DEPARTS가 되지만 기존 violation_at은 보존한다.
Definition at line 358 of file EventDatabase.cpp.
References db_, executeSqlUnlocked(), and mutex_.
Referenced by parking_timer::ParkingSlotManager::handleExit().
executeSqlUnlocked()
void parking_timer::EventDatabase::executeSqlUnlocked (const std::string & sql) private
준비 과정이 필요 없는 SQL 문자열을 SQLite 연결에서 직접 실행한다.
Parameters
[in] sql 실행할 하나 이상의 SQL 문장.
Exceptions
std::runtime_error SQLite 실행이 실패한 경우.
Warning
이 함수는 mutex를 잡지 않는다. 호출자는 필요할 경우 mutex_를 이미 보유해야 하며, 생성자처럼 객체가 아직 공유되지 않은 시점에만 예외가 가능하다.
Definition at line 542 of file EventDatabase.cpp.
References db_.
Referenced by clearTimerLogs(), departActiveByZone(), EventDatabase(), and initialize().
findActiveByZone()
std::optional< LogRecord > parking_timer::EventDatabase::findActiveByZone (int zone_id) const
지정 구역에서 아직 출차하지 않은 세션을 조회한다.
Parameters
[in] zone_id 조회할 충전구역 ID.
Returns
활성 로그 또는 활성 행이 없을 때 std::nullopt.
Exceptions
std::runtime_error SQLite 조회가 실패한 경우.
Definition at line 423 of file EventDatabase.cpp.
References db_, and mutex_.
Referenced by parking_timer::ParkingSlotManager::handleEntry().
findLogById()
std::optional< LogRecord > parking_timer::EventDatabase::findLogById (std::int64_t log_id) const
고유 로그 ID로 주차 세션 한 건을 조회한다.
Parameters
[in] log_id 조회할 timer_log.id.
Returns
해당 로그 또는 존재하지 않을 때 std::nullopt.
Exceptions
std::runtime_error SQLite 조회가 실패한 경우.
Definition at line 450 of file EventDatabase.cpp.
References db_, and mutex_.
Referenced by anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit(), and anonymous_namespace{timer_tests.cpp}::testWorkerContainsCallbackExceptions().
initialize()
void parking_timer::EventDatabase::initialize (const std::filesystem::path & schema_file, const std::filesystem::path & seed_file)
스키마를 생성하고 차량 마스터 테스트 데이터를 멱등하게 삽입한다.
Parameters
[in] schema_file 실행할 DDL 파일 경로.
[in] seed_file 실행할 seed SQL 파일 경로.
Exceptions
std::runtime_error 파일 읽기 또는 SQL 실행에 실패한 경우.
Note
seed는 BEGIN IMMEDIATE 트랜잭션으로 묶고 오류 시 전부 rollback한다.
Definition at line 224 of file EventDatabase.cpp.
References db_, executeSqlUnlocked(), mutex_, and readTextFile().
Referenced by anonymous_namespace{timer_tests.cpp}::initialize().
insertParked()
std::int64_t parking_timer::EventDatabase::insertParked (const std::string & car_number, int zone_id, const std::string & parked_at, const std::string & image_path_1)
EV/PHEV 입차 세션을 PARKED 상태로 INSERT한다.
Parameters
[in] car_number 차량번호.
[in] zone_id 충전구역 ID.
[in] parked_at 최초 주차 판정 UTC 시각.
[in] image_path_1 최초 증거 이미지 경로.
Returns
새 timer_log 행의 64비트 ID.
Exceptions
std::runtime_error SQL 제약조건 또는 실행 오류가 발생한 경우.
Definition at line 283 of file EventDatabase.cpp.
References db_, and mutex_.
Referenced by parking_timer::ParkingSlotManager::handleEntry(), anonymous_namespace{timer_tests.cpp}::testEarlierDeadlineWakesWorker(), and anonymous_namespace{timer_tests.cpp}::testWorkerContainsCallbackExceptions().
listLogs()
std::vector< LogRecord > parking_timer::EventDatabase::listLogs () const
모든 타이머 로그를 생성 순서대로 조회한다.
Returns
id 오름차순의 로그 목록.
Exceptions
std::runtime_error 조회 도중 SQLite 오류가 발생한 경우.
Definition at line 475 of file EventDatabase.cpp.
References db_, and mutex_.
Referenced by anonymous_namespace{main.cpp}::printLogs(), and anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit().
listVehicles()
std::vector< std::pair< std::string, std::string > > parking_timer::EventDatabase::listVehicles () const
차량 마스터의 차량번호와 차량 종류를 모두 조회한다.
Returns
차량번호 오름차순의 (car_number, vehicle_type) 목록.
Exceptions
std::runtime_error 조회 도중 SQLite 오류가 발생한 경우.
Definition at line 503 of file EventDatabase.cpp.
References db_, and mutex_.
Referenced by anonymous_namespace{main.cpp}::printVehicles().
markViolation()
bool parking_timer::EventDatabase::markViolation (std::int64_t log_id, const std::string & violation_at, const std::string & image_path_2)
아직 활성인 주차 세션을 위반 상태로 조건부 갱신한다.
Parameters
[in] log_id 갱신할 불변 주차 세션 ID.
[in] violation_at 최초 deadline 도달 UTC 시각.
[in] image_path_2 위반 증거 이미지 경로.
Returns
정확히 한 행이 갱신됐으면 true. 이미 출차/취소됐으면 false.
Exceptions
std::runtime_error SQLite UPDATE가 실패한 경우.
Note
WHERE 조건 자체가 출차와 만료의 경합을 해결하는 최종 안전장치다.
Definition at line 310 of file EventDatabase.cpp.
References db_, and mutex_.
Referenced by parking_timer::TimerManager::processExpired().
operator=()
EventDatabase & parking_timer::EventDatabase::operator= (const EventDatabase &) delete
readTextFile()
std::string parking_timer::EventDatabase::readTextFile (const std::filesystem::path & path) static private
SQL/config 보조 파일 전체를 문자열로 읽는다.
Parameters
[in] path 읽을 파일 경로.
Returns
파일의 전체 바이트 내용.
Exceptions
std::runtime_error 파일을 열 수 없는 경우.
Definition at line 561 of file EventDatabase.cpp.
Referenced by initialize().
Field Documentation
db_
sqlite3* parking_timer::EventDatabase::db_ {} private
Definition at line 55 of file EventDatabase.hpp.
Referenced by cancelUnscheduled(), classifyVehicle(), departActiveByZone(), EventDatabase(), executeSqlUnlocked(), findActiveByZone(), findLogById(), initialize(), insertParked(), listLogs(), listVehicles(), markViolation(), and ~EventDatabase().
mutex_
std::mutex parking_timer::EventDatabase::mutex_ mutable private
Definition at line 56 of file EventDatabase.hpp.
Referenced by cancelUnscheduled(), classifyVehicle(), clearTimerLogs(), departActiveByZone(), findActiveByZone(), findLogById(), initialize(), insertParked(), listLogs(), listVehicles(), and markViolation().
The documentation for this class was generated from the following files:
EventDatabase.hpp
EventDatabase.cpp