주차구역 EV 점유 타이머 API: anonymous_namespace{timer_tests.cpp} Namespace Reference
anonymous_namespace{timer_tests.cpp} Namespace Reference
Functions
void require (const bool condition, const std::string &message)
테스트 조건을 검사하고 실패를 예외로 보고한다.
std::filesystem::path temporaryDatabase (const std::string &label)
테스트별로 충돌 가능성이 낮은 임시 SQLite 경로를 만든다.
void removeDatabaseFiles (const std::filesystem::path &database)
테스트 SQLite 본 파일과 WAL 보조 파일을 최선 노력으로 제거한다.
template<typename Predicate >
bool waitUntil (Predicate predicate, const std::chrono::milliseconds timeout)
비동기 조건이 참이 될 때까지 짧은 간격으로 기다린다.
void initialize (EventDatabase &database)
빌드 디렉터리에 복사된 schema와 seed로 테스트 DB를 초기화한다.
void testEntryViolationAndExit ()
차량 분류부터 입차·만료·출차·lazy deletion까지 전체 수명주기를 검증한다.
void testEarlierDeadlineWakesWorker ()
기존 대기보다 빠른 새 deadline이 worker를 깨우고 먼저 처리되는지 검증한다.
void testWorkerContainsCallbackExceptions ()
위반 publisher callback 예외가 worker 밖으로 전파되지 않는지 검증한다.
Function Documentation
initialize()
void anonymous_namespace{timer_tests.cpp}::initialize (EventDatabase & database)
빌드 디렉터리에 복사된 schema와 seed로 테스트 DB를 초기화한다.
Parameters
[in,out] database 초기화할 열린 DB.
Exceptions
std::runtime_error SQL 파일 읽기 또는 실행이 실패한 경우.
Definition at line 92 of file timer_tests.cpp.
References parking_timer::EventDatabase::initialize().
Referenced by testEarlierDeadlineWakesWorker(), testEntryViolationAndExit(), and testWorkerContainsCallbackExceptions().
removeDatabaseFiles()
void anonymous_namespace{timer_tests.cpp}::removeDatabaseFiles (const std::filesystem::path & database)
테스트 SQLite 본 파일과 WAL 보조 파일을 최선 노력으로 제거한다.
Parameters
[in] database 제거할 DB 본 파일 경로.
Note
cleanup 실패가 원래 테스트 결과를 가리지 않도록 오류 코드는 의도적으로 무시한다.
Definition at line 59 of file timer_tests.cpp.
Referenced by testEarlierDeadlineWakesWorker(), testEntryViolationAndExit(), and testWorkerContainsCallbackExceptions().
require()
void anonymous_namespace{timer_tests.cpp}::require (const bool condition, const std::string & message)
테스트 조건을 검사하고 실패를 예외로 보고한다.
Parameters
[in] condition 통과해야 하는 조건.
[in] message 실패 시 표시할 진단 메시지.
Exceptions
std::runtime_error 조건이 false인 경우.
Definition at line 35 of file timer_tests.cpp.
Referenced by testEarlierDeadlineWakesWorker(), testEntryViolationAndExit(), and testWorkerContainsCallbackExceptions().
temporaryDatabase()
std::filesystem::path anonymous_namespace{timer_tests.cpp}::temporaryDatabase (const std::string & label)
테스트별로 충돌 가능성이 낮은 임시 SQLite 경로를 만든다.
Parameters
[in] label 파일명에서 테스트를 구분할 짧은 라벨.
Returns
시스템 임시 디렉터리 아래의 고유 DB 파일 경로.
Definition at line 47 of file timer_tests.cpp.
Referenced by testEarlierDeadlineWakesWorker(), testEntryViolationAndExit(), and testWorkerContainsCallbackExceptions().
testEarlierDeadlineWakesWorker()
void anonymous_namespace{timer_tests.cpp}::testEarlierDeadlineWakesWorker ()
기존 대기보다 빠른 새 deadline이 worker를 깨우고 먼저 처리되는지 검증한다.
Exceptions
std::runtime_error callback이 오지 않거나 최소 힙 순서가 잘못된 경우.
Definition at line 178 of file timer_tests.cpp.
References initialize(), parking_timer::EventDatabase::insertParked(), parking_timer::ViolationEvent::log_id, removeDatabaseFiles(), require(), parking_timer::TimerManager::schedule(), temporaryDatabase(), and parking_timer::utcNow().
Referenced by main().
testEntryViolationAndExit()
void anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit ()
차량 분류부터 입차·만료·출차·lazy deletion까지 전체 수명주기를 검증한다.
Exceptions
std::runtime_error 기대한 분류나 DB 상태 전이가 하나라도 맞지 않는 경우.
Definition at line 102 of file timer_tests.cpp.
References parking_timer::EntryResult::accepted, parking_timer::EventDatabase::classifyVehicle(), parking_timer::Ev, parking_timer::EventDatabase::findLogById(), parking_timer::ParkingSlotManager::handleEntry(), parking_timer::ParkingSlotManager::handleExit(), initialize(), parking_timer::EventDatabase::listLogs(), parking_timer::NonEv, parking_timer::ParkingSlotManager::pendingTimerCount(), parking_timer::Phev, removeDatabaseFiles(), require(), temporaryDatabase(), parking_timer::Unknown, and waitUntil().
Referenced by main().
testWorkerContainsCallbackExceptions()
void anonymous_namespace{timer_tests.cpp}::testWorkerContainsCallbackExceptions ()
위반 publisher callback 예외가 worker 밖으로 전파되지 않는지 검증한다.
Exceptions
std::runtime_error 오류 callback이 호출되지 않거나 DB 위반 기록이 사라진 경우.
Definition at line 220 of file timer_tests.cpp.
References parking_timer::EventDatabase::findLogById(), initialize(), parking_timer::EventDatabase::insertParked(), removeDatabaseFiles(), require(), parking_timer::TimerManager::schedule(), temporaryDatabase(), and parking_timer::utcNow().
Referenced by main().
waitUntil()
template<typename Predicate > bool anonymous_namespace{timer_tests.cpp}::waitUntil (Predicate predicate, const std::chrono::milliseconds timeout)
비동기 조건이 참이 될 때까지 짧은 간격으로 기다린다.
Template Parameters
Predicate 인자 없이 호출해 bool로 평가할 수 있는 조건 함수 타입.
Parameters
[in] predicate 완료 여부를 검사할 함수 객체.
[in] timeout 기다릴 최대 시간.
Returns
제한시간 안 또는 마지막 검사에서 조건이 참이면 true.
Definition at line 75 of file timer_tests.cpp.
Referenced by testEntryViolationAndExit().