주차구역 EV 점유 타이머 API: parking_timer Namespace Reference
parking_timer Namespace Reference
Namespaces
namespace anonymous_namespace{EventDatabase.cpp}
namespace anonymous_namespace{EventManager.cpp}
namespace anonymous_namespace{RuntimeConfig.cpp}
Data Structures
struct EntryResult
class EventDatabase
class EventManager
struct LogRecord
class ParkingSlotManager
struct RuntimeConfig
struct TimerError
class TimerManager
struct ViolationEvent
Enumerations
enum class VehicleCategory { Ev , Phev , NonEv , Unknown }
Functions
const char * toString (const VehicleCategory category) noexcept
차량 분류 열거형을 로그와 화면에 사용할 문자열로 변환한다.
std::string utcNow ()
현재 시스템 시각을 밀리초 정밀도의 ISO-8601 UTC 문자열로 만든다.
Enumeration Type Documentation
VehicleCategory
enum class parking_timer::VehicleCategory strong
Enumerator
Ev
Phev
NonEv
Unknown
Definition at line 9 of file Types.hpp.
Function Documentation
toString()
const char * parking_timer::toString (const VehicleCategory category) noexcept
차량 분류 열거형을 로그와 화면에 사용할 문자열로 변환한다.
Parameters
[in] category 변환할 차량 분류 값.
Returns
열거형의 수명과 무관하게 유효한 정적 문자열 포인터.
Note
알 수 없는 열거형 값도 안전하게 UNKNOWN으로 처리하며 예외를 던지지 않는다.
Definition at line 17 of file Types.cpp.
References Ev, NonEv, Phev, and Unknown.
Referenced by anonymous_namespace{main.cpp}::runInteractive().
utcNow()
std::string parking_timer::utcNow ()
현재 시스템 시각을 밀리초 정밀도의 ISO-8601 UTC 문자열로 만든다.
Returns
YYYY-MM-DDTHH:MM:SS.mmmZ 형식의 UTC 시각 문자열.
Note
이 시각은 DB 기록과 관제 표시용이다. 타이머 경과시간 판정은 시스템 시각 변경의 영향을 받지 않도록 steady_clock을 별도로 사용한다.
Definition at line 38 of file Types.cpp.
Referenced by parking_timer::ParkingSlotManager::handleEntry(), parking_timer::ParkingSlotManager::handleExit(), parking_timer::TimerManager::processExpired(), anonymous_namespace{timer_tests.cpp}::testEarlierDeadlineWakesWorker(), and anonymous_namespace{timer_tests.cpp}::testWorkerContainsCallbackExceptions().