주차구역 EV 점유 타이머 API: parking_timer::anonymous_namespace{EventDatabase.cpp} Namespace Reference
parking_timer::anonymous_namespace{EventDatabase.cpp} Namespace Reference
Data Structures
class Statement
sqlite3_stmt의 prepare/finalize 수명을 RAII로 관리하는 내부 래퍼.
Functions
std::string columnText (sqlite3_stmt *statement, const int column)
현재 row의 SQLite TEXT 컬럼을 C++ 문자열로 복사한다.
std::optional< std::string > optionalColumnText (sqlite3_stmt *statement, const int column)
SQL NULL과 실제 문자열을 구분해 optional 문자열로 읽는다.
LogRecord readLogRecord (sqlite3_stmt *statement)
고정된 SELECT 컬럼 순서의 현재 row를 LogRecord로 변환한다.
void requireDone (sqlite3 *database, sqlite3_stmt *statement)
변경 SQL을 한 번 실행하고 정상 완료 여부를 검사한다.
Function Documentation
columnText()
std::string parking_timer::anonymous_namespace{EventDatabase.cpp}::columnText (sqlite3_stmt * statement, const int column)
현재 row의 SQLite TEXT 컬럼을 C++ 문자열로 복사한다.
Parameters
[in] statement SQLITE_ROW를 가리키는 prepared statement.
[in] column 0부터 시작하는 결과 컬럼 인덱스.
Returns
컬럼 문자열. SQL NULL이면 빈 문자열.
Definition at line 108 of file EventDatabase.cpp.
References columnText().
Referenced by columnText(), optionalColumnText(), and readLogRecord().
optionalColumnText()
std::optional< std::string > parking_timer::anonymous_namespace{EventDatabase.cpp}::optionalColumnText (sqlite3_stmt * statement, const int column)
SQL NULL과 실제 문자열을 구분해 optional 문자열로 읽는다.
Parameters
[in] statement SQLITE_ROW를 가리키는 prepared statement.
[in] column 0부터 시작하는 결과 컬럼 인덱스.
Returns
SQL NULL이면 std::nullopt, 아니면 컬럼 문자열.
Definition at line 121 of file EventDatabase.cpp.
References columnText(), and optionalColumnText().
Referenced by optionalColumnText(), and readLogRecord().
readLogRecord()
LogRecord parking_timer::anonymous_namespace{EventDatabase.cpp}::readLogRecord (sqlite3_stmt * statement)
고정된 SELECT 컬럼 순서의 현재 row를 LogRecord로 변환한다.
Parameters
[in] statement timer_log 조회 결과의 현재 row.
Returns
모든 로그 컬럼이 채워진 값 객체.
Warning
호출 SQL의 컬럼 순서는 이 함수의 0~9 인덱스 순서와 일치해야 한다.
Definition at line 136 of file EventDatabase.cpp.
References parking_timer::LogRecord::car_number, columnText(), parking_timer::LogRecord::departed_at, parking_timer::LogRecord::id, parking_timer::LogRecord::image_path_1, parking_timer::LogRecord::image_path_2, parking_timer::LogRecord::is_canceled, optionalColumnText(), parking_timer::LogRecord::parked_at, readLogRecord(), parking_timer::LogRecord::status, parking_timer::LogRecord::violation_at, and parking_timer::LogRecord::zone_id.
Referenced by readLogRecord().
requireDone()
void parking_timer::anonymous_namespace{EventDatabase.cpp}::requireDone (sqlite3 * database, sqlite3_stmt * statement)
변경 SQL을 한 번 실행하고 정상 완료 여부를 검사한다.
Parameters
[in] database 오류 메시지를 얻을 SQLite 연결.
[in] statement 실행할 prepared statement.
Exceptions
std::runtime_error 실행 결과가 SQLITE_DONE이 아닌 경우.
Definition at line 158 of file EventDatabase.cpp.
References requireDone().
Referenced by requireDone().