주차구역 EV 점유 타이머 API: anonymous_namespace{main.cpp} Namespace Reference
anonymous_namespace{main.cpp} Namespace Reference
Data Structures
struct Options
명령행에서 선택적으로 지정할 실행 옵션 모음.
Functions
long long parsePositiveInteger (const std::string &value, const std::string &option)
CLI 문자열을 양의 정수로 엄격하게 변환한다.
Options parseArguments (const int argc, char *argv[])
프로그램 명령행 인자를 구조화된 옵션으로 해석한다.
std::filesystem::path findResource (const std::optional< std::filesystem::path > &explicit_path, const std::vector< std::filesystem::path > &candidates, const std::string &description)
명시 경로 또는 우선순위 후보 목록에서 리소스를 찾는다.
std::filesystem::path executableDirectory (const char *argv0)
현재 실행 중인 바이너리가 위치한 디렉터리를 구한다.
void printUsage (const char *executable)
프로그램 명령행 옵션 도움말을 출력한다.
std::string displayOptional (const std::optional< std::string > &value)
nullable 문자열을 표 출력용 값으로 변환한다.
void printLogs (const EventDatabase &database)
현재 timer_log 내용을 사람이 읽을 수 있는 표로 출력한다.
void printVehicles (const EventDatabase &database)
테스트 차량 마스터의 차량번호와 종류를 출력한다.
void printInteractiveHelp ()
대화형 시뮬레이터가 지원하는 명령 목록을 출력한다.
void runInteractive (ParkingSlotManager &slots, EventDatabase &database)
표준 입력에서 홀센서/번호판 이벤트를 흉내 내는 REPL을 실행한다.
void runDemo (ParkingSlotManager &slots, EventDatabase &database, const std::chrono::milliseconds timeout)
EV 만료와 PHEV 조기 출차를 함께 보여주는 자동 시나리오를 실행한다.
Function Documentation
displayOptional()
std::string anonymous_namespace{main.cpp}::displayOptional (const std::optional< std::string > & value)
nullable 문자열을 표 출력용 값으로 변환한다.
Parameters
[in] value 표시할 optional 문자열.
Returns
값이 있으면 해당 문자열, SQL NULL에 대응하면 -.
Definition at line 179 of file main.cpp.
Referenced by printLogs().
executableDirectory()
std::filesystem::path anonymous_namespace{main.cpp}::executableDirectory (const char * argv0)
현재 실행 중인 바이너리가 위치한 디렉터리를 구한다.
Parameters
[in] argv0 /proc/self/exe를 사용할 수 없을 때 fallback할 프로그램 경로.
Returns
실행 파일의 부모 디렉터리.
Exceptions
std::filesystem::filesystem_error fallback 절대경로 계산이 실패한 경우.
Note
Linux에서는 현재 작업 디렉터리나 PATH 호출 방식과 무관한 /proc/self/exe를 우선한다.
Definition at line 143 of file main.cpp.
Referenced by main().
findResource()
std::filesystem::path anonymous_namespace{main.cpp}::findResource (const std::optional< std::filesystem::path > & explicit_path, const std::vector< std::filesystem::path > & candidates, const std::string & description)
명시 경로 또는 우선순위 후보 목록에서 리소스를 찾는다.
Parameters
[in] explicit_path CLI로 직접 지정한 선택 경로.
[in] candidates 명시 경로가 없을 때 순서대로 검사할 후보 경로.
[in] description 오류 메시지에 표시할 리소스 설명.
Returns
존재가 확인된 경로.
Exceptions
std::runtime_error 명시 경로가 없거나 어떤 후보도 존재하지 않는 경우.
std::filesystem::filesystem_error 파일시스템 검사 자체가 실패한 경우.
Note
잘못된 명시 경로는 조용히 fallback하지 않는다. 명시 경로가 없을 때만 후보의 앞쪽부터 선택하므로 벡터 순서가 곧 탐색 우선순위다.
Definition at line 116 of file main.cpp.
Referenced by main().
parseArguments()
Options anonymous_namespace{main.cpp}::parseArguments (const int argc, char * argv[])
프로그램 명령행 인자를 구조화된 옵션으로 해석한다.
Parameters
[in] argc main()에서 받은 인자 개수.
[in] argv main()에서 받은 NUL 종료 인자 배열.
Returns
파싱된 선택 옵션.
Exceptions
std::invalid_argument 옵션 값이 빠졌거나 잘못됐거나 알 수 없는 옵션인 경우.
Definition at line 70 of file main.cpp.
References anonymous_namespace{main.cpp}::Options::config_file, anonymous_namespace{main.cpp}::Options::database_path, anonymous_namespace{main.cpp}::Options::demo, anonymous_namespace{main.cpp}::Options::help, parsePositiveInteger(), anonymous_namespace{main.cpp}::Options::reset_logs, anonymous_namespace{main.cpp}::Options::sql_directory, and anonymous_namespace{main.cpp}::Options::timeout.
Referenced by main().
parsePositiveInteger()
long long anonymous_namespace{main.cpp}::parsePositiveInteger (const std::string & value, const std::string & option)
CLI 문자열을 양의 정수로 엄격하게 변환한다.
Parameters
[in] value 변환할 문자열.
[in] option 오류 메시지에 표시할 옵션 또는 명령 이름.
Returns
변환된 1 이상의 정수.
Exceptions
std::invalid_argument 숫자가 아니거나 후행 문자가 있거나 0 이하인 경우.
Definition at line 48 of file main.cpp.
Referenced by parseArguments(), and runInteractive().
printInteractiveHelp()
void anonymous_namespace{main.cpp}::printInteractiveHelp ()
대화형 시뮬레이터가 지원하는 명령 목록을 출력한다.
Definition at line 221 of file main.cpp.
Referenced by runInteractive().
printLogs()
void anonymous_namespace{main.cpp}::printLogs (const EventDatabase & database)
현재 timer_log 내용을 사람이 읽을 수 있는 표로 출력한다.
Parameters
[in] database 조회할 이벤트 DB.
Exceptions
std::runtime_error DB 조회가 실패한 경우.
Definition at line 189 of file main.cpp.
References displayOptional(), and parking_timer::EventDatabase::listLogs().
Referenced by runDemo(), and runInteractive().
printUsage()
void anonymous_namespace{main.cpp}::printUsage (const char * executable)
프로그램 명령행 옵션 도움말을 출력한다.
Parameters
[in] executable 도움말 첫 줄에 표시할 실행 파일 이름.
Definition at line 160 of file main.cpp.
Referenced by main().
printVehicles()
void anonymous_namespace{main.cpp}::printVehicles (const EventDatabase & database)
테스트 차량 마스터의 차량번호와 종류를 출력한다.
Parameters
[in] database 조회할 이벤트 DB.
Exceptions
std::runtime_error DB 조회가 실패한 경우.
Definition at line 212 of file main.cpp.
References parking_timer::EventDatabase::listVehicles().
Referenced by runInteractive().
runDemo()
void anonymous_namespace{main.cpp}::runDemo (ParkingSlotManager & slots, EventDatabase & database, const std::chrono::milliseconds timeout)
EV 만료와 PHEV 조기 출차를 함께 보여주는 자동 시나리오를 실행한다.
Parameters
[in,out] slots 입차·출차와 타이머를 처리할 주차구역 관리자.
[in] database 마지막 상태를 출력할 DB.
[in] timeout 데모에서 사용할 장기점유 제한시간.
Exceptions
std::invalid_argument 데모 입력 또는 timeout이 유효하지 않은 경우.
std::runtime_error DB나 타이머 작업이 실패한 경우.
Definition at line 314 of file main.cpp.
References parking_timer::ParkingSlotManager::handleEntry(), parking_timer::ParkingSlotManager::handleExit(), and printLogs().
Referenced by main().
runInteractive()
void anonymous_namespace{main.cpp}::runInteractive (ParkingSlotManager & slots, EventDatabase & database)
표준 입력에서 홀센서/번호판 이벤트를 흉내 내는 REPL을 실행한다.
Parameters
[in,out] slots 입차·출차 명령을 전달할 주차구역 관리자.
[in] database 로그와 차량 마스터를 출력할 DB.
Note
개별 명령의 예외는 오류 메시지로 바꾸고 다음 명령을 계속 받는다. EOF 또는 quit 명령이 들어오면 반환한다.
Definition at line 242 of file main.cpp.
References parking_timer::ParkingSlotManager::handleEntry(), parking_timer::ParkingSlotManager::handleExit(), parking_timer::EntryResult::message, parsePositiveInteger(), parking_timer::ParkingSlotManager::pendingTimerCount(), printInteractiveHelp(), printLogs(), printVehicles(), and parking_timer::toString().
Referenced by main().