주차구역 EV 점유 타이머 API: parking_timer::anonymous_namespace{RuntimeConfig.cpp} Namespace Reference
parking_timer::anonymous_namespace{RuntimeConfig.cpp} Namespace Reference
Functions
std::string trim (std::string value)
문자열 양 끝의 공백과 개행 문자를 제거한다.
std::chrono::milliseconds parseTimeout (const std::string &value, const std::string_view source)
초 단위 설정 문자열을 양수 밀리초 duration으로 변환한다.
void applyValue (RuntimeConfig &config, const std::string &key, const std::string &value, const std::string_view source)
하나의 KEY=VALUE 설정을 런타임 설정 객체에 반영한다.
Function Documentation
applyValue()
void parking_timer::anonymous_namespace{RuntimeConfig.cpp}::applyValue (RuntimeConfig & config, const std::string & key, const std::string & value, const std::string_view source)
하나의 KEY=VALUE 설정을 런타임 설정 객체에 반영한다.
Parameters
[in,out] config 갱신할 런타임 설정.
[in] key 설정 키.
[in] value 설정 값.
[in] source 오류 메시지에 표시할 파일 또는 환경 출처.
Exceptions
std::runtime_error timeout이 잘못됐거나 DB 경로가 빈 문자열인 경우.
Note
알 수 없는 키는 향후 설정 확장을 위해 현재는 무시한다.
Definition at line 60 of file RuntimeConfig.cpp.
References applyValue(), parking_timer::RuntimeConfig::database_path, parking_timer::RuntimeConfig::parking_timeout, and parseTimeout().
Referenced by applyValue().
parseTimeout()
std::chrono::milliseconds parking_timer::anonymous_namespace{RuntimeConfig.cpp}::parseTimeout (const std::string & value, const std::string_view source)
초 단위 설정 문자열을 양수 밀리초 duration으로 변환한다.
Parameters
[in] value 숫자로 해석할 설정값.
[in] source 오류 메시지에 표시할 설정 출처 또는 키 이름.
Returns
입력 초를 나타내는 std::chrono::milliseconds 값.
Exceptions
std::runtime_error 정수가 아니거나 0 이하인 경우.
Definition at line 35 of file RuntimeConfig.cpp.
References parseTimeout().
Referenced by applyValue(), and parseTimeout().
trim()
std::string parking_timer::anonymous_namespace{RuntimeConfig.cpp}::trim (std::string value)
문자열 양 끝의 공백과 개행 문자를 제거한다.
Parameters
[in] value 정리할 문자열. 함수 내부에서 이동·수정할 수 있도록 값으로 받는다.
Returns
앞뒤 공백이 제거된 문자열. 공백뿐이면 빈 문자열.
Definition at line 18 of file RuntimeConfig.cpp.
References trim().
Referenced by trim().