주차구역 EV 점유 타이머 API: timer_tests.cpp File Reference
timer_tests.cpp File Reference
#include "parking_timer/EventDatabase.hpp"
#include "parking_timer/EventManager.hpp"
#include "parking_timer/ParkingSlotManager.hpp"
#include "parking_timer/TimerManager.hpp"
#include "parking_timer/Types.hpp"
#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <iostream>
#include <mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>
Namespaces
namespace anonymous_namespace{timer_tests.cpp}
Functions
void anonymous_namespace{timer_tests.cpp}::require (const bool condition, const std::string &message)
테스트 조건을 검사하고 실패를 예외로 보고한다.
std::filesystem::path anonymous_namespace{timer_tests.cpp}::temporaryDatabase (const std::string &label)
테스트별로 충돌 가능성이 낮은 임시 SQLite 경로를 만든다.
void anonymous_namespace{timer_tests.cpp}::removeDatabaseFiles (const std::filesystem::path &database)
테스트 SQLite 본 파일과 WAL 보조 파일을 최선 노력으로 제거한다.
template<typename Predicate >
bool anonymous_namespace{timer_tests.cpp}::waitUntil (Predicate predicate, const std::chrono::milliseconds timeout)
비동기 조건이 참이 될 때까지 짧은 간격으로 기다린다.
void anonymous_namespace{timer_tests.cpp}::initialize (EventDatabase &database)
빌드 디렉터리에 복사된 schema와 seed로 테스트 DB를 초기화한다.
void anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit ()
차량 분류부터 입차·만료·출차·lazy deletion까지 전체 수명주기를 검증한다.
void anonymous_namespace{timer_tests.cpp}::testEarlierDeadlineWakesWorker ()
기존 대기보다 빠른 새 deadline이 worker를 깨우고 먼저 처리되는지 검증한다.
void anonymous_namespace{timer_tests.cpp}::testWorkerContainsCallbackExceptions ()
위반 publisher callback 예외가 worker 밖으로 전파되지 않는지 검증한다.
int main ()
모든 타이머 단위/통합 테스트를 실행한다.
Function Documentation
main()
int main ()
모든 타이머 단위/통합 테스트를 실행한다.
Returns
모든 테스트 통과 시 0, 첫 실패를 포착하면 1.
Definition at line 262 of file timer_tests.cpp.
References anonymous_namespace{timer_tests.cpp}::testEarlierDeadlineWakesWorker(), anonymous_namespace{timer_tests.cpp}::testEntryViolationAndExit(), and anonymous_namespace{timer_tests.cpp}::testWorkerContainsCallbackExceptions().